### ISSUE TITLE
RunGulpBuild target too late when deploying with msbuild?

### ISSUE THREAD

**Issue by dhobi** [kmees/MSBuild.NodeTools#25]
I have the issue that when I deploy a MVC project from Jenkins (with msbuild), the gulp target "RunGulpBuild" is executed after the publishing.
When publishing with Visual Studio I don't have that effect. 

I'm not sure if VS does the publish with msbuild or with msbuild and msdeploy sequentially. If the latter is the case that would at least explain the different behaviour.

The target execution hook seems to be right for me (BeforeTargets="Build") but is this also true in a "web publishing context"? Would it make sense to just define an earlier execution time?

**Comment by kmees** [comment]
I don't have any experience with Jenkins and there really is lack of documentation on which tasks get executed when. I don't want to switch the hooks again since there are pros and cons for each of them (see https://github.com/kmees/MSBuild.NodeTools/issues/10). I guess your best bet is to fork and change it to whatever works for you.
